// Workflow creation module
export async function createWorkflow(page) {
  await page.getByRole('button', { name: 'Define Workflow' }).click();

  await page.getByText('Click to Add').first().click();
  await page.getByRole('button', { name: 'Right Action' }).click();
  await page.locator('div').filter({ hasText: /^Start state$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Right Action' }).nth(1).click();
  await page.getByText('Start stateProcess stateAction').click();
  await page.getByText('Start stateProcess stateAction').click();
  await page.getByText('Click to Add').nth(2).click();
  await page.getByText('Click to Add').nth(2).click();
  await page.getByRole('button', { name: 'Right Action' }).nth(2).click();
  await page.getByRole('button', { name: 'Left Action' }).nth(3).click();
  await page.getByRole('button', { name: 'Right Action' }).nth(1).click();
  await page.getByRole('button', { name: 'Left Action' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).fill('Pending for verification');
  await page.locator('rect').nth(4).click();
  await page.getByRole('textbox', { name: 'Mention action name' }).click();
  await page.getByRole('textbox', { name: 'Mention action name' }).fill('Resolve');
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Citizen' }).check();
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Employee' }).check();
  await page.getByRole('switch').first().click();
  await page.getByRole('switch').nth(1).click();
  await page.getByRole('heading', { name: 'Process state' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).fill('Resolved');
  await page.locator('rect').nth(5).click();
  await page.getByRole('textbox', { name: 'Mention action name' }).click();
  await page.getByRole('textbox', { name: 'Mention action name' }).fill('Feedback');
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Citizen' }).check();
  await page.getByText('Action name * DescriptionAssigned role * 1 SelectedAdd New RoleAdd').click();
  await page.getByRole('checkbox', { name: 'Select option: Citizen' }).uncheck();
  await page.getByRole('checkbox', { name: 'Select option: Employee' }).check();
  await page.getByRole('checkbox', { name: 'Select option: Citizen' }).check();
  await page.getByText('Add New checklist').click();
  await page.getByRole('textbox', { name: 'Please type your question here' }).click();
  await page.getByRole('textbox', { name: 'Please type your question here' }).fill('Rate service');
  await page.getByRole('textbox', { name: 'Option 1' }).click();
  await page.getByRole('textbox', { name: 'Option 1' }).fill('1');
  await page.getByRole('button', { name: 'Add Options for Question' }).click();
  await page.getByRole('button', { name: 'Add Options for Question' }).click();
  await page.getByRole('textbox', { name: 'Option 2' }).click();
  await page.getByRole('textbox', { name: 'Option 2' }).fill('2');
  await page.getByRole('textbox', { name: 'Option 3' }).click();
  await page.getByRole('textbox', { name: 'Option 3' }).fill('3');
  await page.getByRole('button', { name: 'Add Options for Question' }).click();
  await page.getByRole('textbox', { name: 'Option 4' }).click();
  await page.getByRole('textbox', { name: 'Option 4' }).fill('4');
  await page.getByRole('button', { name: 'Add Options for Question' }).click();
  await page.getByRole('textbox', { name: 'Option 5' }).click();
  await page.getByRole('textbox', { name: 'Option 5' }).fill('5');
  await page.getByRole('button', { name: 'Add Question' }).click();
  await page.getByRole('textbox', { name: 'Please type your question here' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Please type your question here' }).nth(1).fill('Feedback to improve service');
  await page.getByRole('button', { name: 'Select an option' }).nth(3).click();
  await page.getByRole('button', { name: 'Text' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('heading', { name: 'End state' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).fill('End');
  await page.locator('g:nth-child(4) > rect').click();
  await page.getByRole('textbox', { name: 'Mention action name' }).click();
  await page.getByRole('textbox', { name: 'Mention action name' }).fill('Reject');
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Citizen' }).check();
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Employee' }).check();
  await page.getByText('Add New checklist').click();
  await page.getByRole('textbox', { name: 'Please type your question here' }).click();
  await page.getByRole('textbox', { name: 'Please type your question here' }).fill('Reason for rejection');
  await page.locator('#servicedesigner-workflow-standalone-form-field').getByRole('button', { name: 'Select an option' }).click();
  await page.getByRole('button', { name: 'Text' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('heading', { name: 'End state' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).fill('Rejected');
  await page.getByRole('heading', { name: 'Start state' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).click();
  await page.getByRole('textbox', { name: 'Mention state name' }).fill('create');
  await page.locator('g').filter({ hasText: 'Action' }).locator('rect').click();
  await page.getByRole('textbox', { name: 'Mention action name' }).click();
  await page.getByRole('textbox', { name: 'Mention action name' }).fill('Applied');
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Citizen' }).check();
  await page.getByRole('textbox', { name: 'Search options in' }).click();
  await page.getByRole('checkbox', { name: 'Select option: Employee' }).check();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
}
